version: '3.8'

services:
  # server:
  #   build:
  #      context: ./backend
  #   command: gunicorn src.app.main:app --bind 0.0.0.0:5000 -w 4 -k uvicorn.workers.UvicornWorker
  #   expose:
  #     - 5000
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.server.rule=Host(`test.localhost.com`)"

  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: npm run start -- -p 3000
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    expose:
      - 3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.client.rule=Host(`test.localhost.com`)"
      - "traefik.http.routers.client.entrypoints=websecure"
      - "traefik.http.routers.client.tls=true"
      - "traefik.http.routers.client.tls.certresolver=letsencrypt"

  traefik:
    image: traefik:v2.2
    ports:
      - "8080:8080"
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "$PWD/traefik.prod.toml:/etc/traefik/traefik.toml"