version: '3.8'

services:
  server:
    build:
       context: ./backend
    command: gunicorn src.app.main:app --bind 0.0.0.0:5000 -w 1 -k uvicorn.workers.UvicornWorker
    extra_hosts:
      - 'host:${HOST_IP?Variable not set}' # Allow docker to talk to local postgres
    environment:
      - DATABASE_URL=postgresql://newsletter:newsletter@${HOST_IP?Variable not set}:5432/newsletter_db_dev
    expose:
      - 5000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.server.rule=Host(`api.localhost.com`)"
      - "traefik.http.routers.server.entrypoints=web"

  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: npm run start -- -p 3000
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    expose:
      - 3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.client.rule=Host(`test.localhost.com`)"
      - "traefik.http.routers.client.entrypoints=web"

  traefik:
    image: traefik:v2.2
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "$PWD/traefik.dev.toml:/etc/traefik/traefik.toml"