version: '3.8'

services:
  server:
    build:
       context: ./backend
       dockerfile: Dockerfile
    command: gunicorn src.app.main:app --bind 0.0.0.0:5000 -w 1 -k uvicorn.workers.UvicornWorker
    extra_hosts:
      - 'host:${HOST_IP?Variable not set}' # Allow docker to talk to local postgres
    environment:
      - DATABASE_URL=postgresql://newsletter:newsletter@host:5432/newsletter_db_dev
    ports:
      - 5000:5000
    expose:
      - 5000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.server.rule=Host(`api.mewslet.com`)"
      - "traefik.http.routers.server.entrypoints=websecure"
      - "traefik.http.routers.server.tls=true"
      - "traefik.http.routers.server.tls.certresolver=letsencrypt"

  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: npm run start -- -p 3000
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    restart: unless-stopped
    expose:
      - 3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.client.rule=Host(`mewslet.com`, `www.mewslet.com`)"
      - "traefik.http.routers.client.entrypoints=websecure"
      - "traefik.http.routers.client.tls=true"
      - "traefik.http.routers.client.tls.certresolver=letsencrypt"

  traefik:
    image: traefik:v2.2
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "$PWD/traefik.prod.toml:/etc/traefik/traefik.toml"