[entryPoints]
  [entryPoints.client]
    address = ":80"
  [entryPoints.server]
    address = ":5000"

[api]
insecure = true

[log]
level = "DEBUG"

[accessLog]

[providers]
  [providers.docker]
    exposedByDefault = false