[entryPoints]
  [entryPoints.server]
    address = ":80"
  [entryPoints.server.http]
    [entryPoints.server.http.redirections]
      [entryPoints.server.http.redirections.entryPoint]
        to = "serversecure"
        scheme = "https"

  [entryPoints.serversecure]
    address = ":443"

[accessLog]

[providers]
  [providers.docker]
    exposedByDefault = false

[certificatesResolvers.letsencrypt.acme]
  email = "kevinchang@live.ca"
  storage= "acme.json"
  [certificatesResolvers.letsencrypt.acme.httpChallenge]
    entryPoint = "server"