[entryPoints]
  [entryPoints.client]
    address = ":80"
  [entryPoints.client.http]
    [entryPoints.client.http.redirections]
      [entryPoints.client.http.redirections.entryPoint]
        to = "clientsecure"
        scheme = "https"

  [entryPoints.clientsecure]
    address = ":443"

[accessLog]

[providers]
  [providers.docker]
    exposedByDefault = false

[certificatesResolvers.letsencrypt.acme]
  email = "kevinchang@live.ca"
  storage= "acme.json"
  [certificatesResolvers.letsencrypt.acme.httpChallenge]
    entryPoint = "client"